apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-cart-pvc
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  
  

